### ISSUE TITLE
Unable to Save as SVX

### ISSUE THREAD

**Issue by Pete-the-Geek** [patrickbwarren/inkscape-survex-export#1] opened 2017-10-18 20:26 UTC
I loaded the Mossdale Caverns map that is provided with this build and I get the following error when I run Save As -> SVX

"Traceback (most recent call last):
  File "svx_output.py", line 122, in <module>
    imgfile = os.path.split(el.attrib['{%s}absref' % inkex.NSS[u'sodipodi']])[1]
  File "src/lxml/lxml.etree.pyx", line 2467, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70679)
KeyError: u'{http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd}absref'"

**Comment by patrickbwarren** [comment] 2017-10-18 21:04
Thanks.  I'll look into it.  I did come across a problem like this just
recently when the image was embedded rather than linked, so it's possible
the error can be cured by loading the image as linked but I obviously need
to catch this case properly (if that is indeed the problem). -- Patrick

**Comment by patrickbwarren** [comment] 2017-10-19 07:58
I couldn't reproduce the error but agree the code needs to catch the case where the absref is missing.  This is now fixed in svx_output.py, which should be reinstalled to the inkscape extensions directory overwriting the previous version.  This new version first checks for the existence of the absref element, before using it to assign the image file name which is reported in the generated svx. If the absref element is not found no image file name is reported.

**Comment by Pete-the-Geek** [comment] 2017-10-19 09:20
Thanks Patrick.
I will re-apply the .py file (hopefully tonight) and will let you know.
If I get any errors, I will detail my setup in case it is a Windows / processor / something else issue.

Many thanks

**Comment by Pete-the-Geek** [comment] 2017-10-19 19:26
Error still occurs but this time there is a different message

"Encountered a PathError:
No paths found at all!
No survex file was generated"

I am running 
Windows 10 Home edition
64bit i7 processor
Inkscape is 32bit version but the same occurs with the 64bit version too.

Is there anything else you would like me to try?
Any idea the path that it is looking for? I could try and put it in the PATH variable?

**Comment by patrickbwarren** [comment] 2017-10-20 20:27
Not sure I understand what's going on here.  I was working in linux (Fedora) but I've now tried in Windows 10, first with Inkscape 0.91 then upgraded to 0.92, and in both cases the svx export works properly with `mossdale_ulsaj89.svg`.  The PathError that's been thrown in your test is a custom error generated by the python export code itself (see `svx_export.py`) when it is unable to find any paths in the svg file.  Can you send me the svg file you are using?  In the mean time I noticed my old copy of survex was unable to process the svx file which has the coordinate system `*cs` commands added, so I'll add a note to that effect in the REAMDE.

**Comment by Pete-the-Geek** [comment] 2017-10-22 21:01
Maybe it is that I am not getting the "paths" correct as mossdale_ulsaj89.svg worked but when I opened farcountry........png and draw a path in red, I get that error. Am I missing something?

**Comment by patrickbwarren** [comment] 2020-05-17 21:25
The code was completely rewritten for Inkscape 1.0, using the all-new inkex python API, so these error might now be fixed.

**Closed as completed by patrickbwarren** 2020-05-17 21:25 UTC
